### ISSUE TITLE
./gradlew runDev reload error

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#321]
Seeing the following stack trace in the console whenever I save a ts file. Workflow still works fine.

```
org.jooby.Err: Not Found(404): No such URL.
        at common.RedirectException.notFoundError(RedirectException.java:67)
        at common.RedirectException.notFoundError(RedirectException.java:71)
        at controllers.Profile.lambda$configure$0(Profile.java:95)
        at org.jooby.Route$OneArgHandler.handle(Route.java:1818)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
        at org.jooby.internal.RouteChain.next(RouteChain.java:262)
        at org.jooby.Route$Chain.next(Route.java:2164)
        at org.jooby.internal.handlers.FlashScopeHandler.handle(FlashScopeHandler.java:262)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
        at org.jooby.internal.RouteChain.next(RouteChain.java:262)
        at org.jooby.Route$Chain.next(Route.java:2164)
        at org.jooby.Route$Before.handle(Route.java:1925)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
        at org.jooby.internal.RouteChain.next(RouteChain.java:262)
        at org.jooby.Route$Chain.next(Route.java:2164)
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
        at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by nedtwigg** [comment]
This is fine.  The hotreload is making a request to the server, not sure what the purpose of the request is, but I think it's a notification "in case you care server, I'm starting over".  I just added an error message so that the log will at least show what path was requested, but we can safely ignore this.
